#!/bin/bash
# /etc/init.d/wm2celery

### BEGIN INIT INFO
# Provides:   whatmanager2
# Required-Start: $local_fs $remote_fs
# Required-Stop:  $local_fs $remote_fs
# Should-Start:   $network
# Should-Stop:    $network
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Short-Description:   Run Celery for WhatManager2
# Description:    Runs Celery on a detached screen session for WhatManager2.
### END INIT INFO

USER="USERNAME"

case "$1" in

  start)
        echo "Starting Celery for WhatManager2"
        sudo -H -u $USER screen -dmS WM2Celery /usr/bin/python /opt/WhatManager2/manage.py celery worker --loglevel=info --concurrency=1
        ;;
  stop)
        echo "Stopping Celery for WhatManager2"
        PID=`ps -ef | grep manage.py | grep pts | grep -v grep | awk '{print $2}'`
        kill -9 $PID
        ;;

  restart|force-reload)
        echo "Restarting $screen"
        PID=`ps -ef | grep manage.py | grep pts | grep -v grep | awk '{print $2}'`
        kill -9 $PID
        sleep 2
        sudo -H -u $USER screen -dmS WM2Celery /usr/bin/python /opt/WhatManager2/manage.py celery worker --loglevel=info --concurrency=1
        ;;
  *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart}" >&2
        exit 1
        ;;
esac
exit 0