# Generated by Django 2.1.4 on 2018-12-09 22:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookupload',
            name='book_data',
            field=models.FileField(upload_to='book_data'),
        ),
        migrations.AlterField(
            model_name='bookupload',
            name='cover_url',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Cover URL'),
        ),
        migrations.AlterField(
            model_name='bookupload',
            name='isbn',
            field=models.CharField(max_length=17, null=True, validators=[django.core.validators.RegexValidator('^(97(8|9)-?)?\\d{9}(\\d|X)$')], verbose_name='ISBN'),
        ),
    ]
