# Generated by Django 2.1.4 on 2018-12-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginDataCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QobuzUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('qobuz_album_id', models.CharField(max_length=64)),
                ('state', models.IntegerField()),
                ('upload_pickle', models.BinaryField()),
                ('download_task_id', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
