#!/bin/sh

SYNC_URL="${URL_SCHEME}://${URL_PROJECT_NAME}_app:${URL_PORT}${URL_PATH}/json/sync"

while true; do
	curl --silent --user "$SYNC_USER":"$SYNC_PASS" --connect-timeout 60 \
	     --max-time 120 "$SYNC_URL"
	sleep "$SYNC_INTERVAL"
done
